### ISSUE TITLE
what is the form of Wikipedia ? xml or json or text?

### ISSUE THREAD

**Issue by chendi1995** [vered1986/hypernymy#3]
thanks. I just use the xml but it failed. it says "ValueError: Sentence boundaries unset. You can add the 'sentencizer' component to the pipeline with: nlp.add_pipe(nlp.create_pipe('sentencizer')) Alternatively, add the dependency parser, or set sentence boundaries by setting doc[i].sent_start "

**Comment by vered1986** [comment]
Thanks for pointing this out! I didn't realize it's not described here: you first need to convert the XML to text using either [this](https://github.com/rmetzger/wikipedia-to-bdc/blob/master/src/de/robertmetzger/Wikipedia2Txt.java) or [this](https://github.com/attardi/wikiextractor).
