### ISSUE TITLE
wikipedia eump file

### ISSUE THREAD

**Issue by wt123u** [vered1986/hypernymy#4]
Hey  Vered,
I am very interested in trying your code too. but i don't know the format of wikipedia dump file.  Is it xml or json ?

**Comment by vered1986** [comment]
Hi @wt123u,

I downloaded the XML dump and converted it to a text corpus. You can do so as suggested [here](http://trulymadlywordly.blogspot.co.il/2011/03/creating-text-corpus-from-wikipedia.html) or using the [WikiExtractor](https://github.com/attardi/wikiextractor).

You can follow the [detailed guide](https://github.com/vered1986/LexNET/wiki/Detailed-Guide) (from our follow-up project). If something is missing or doesn't work using the instructions from there, let me know!

**Comment by wt123u** [comment]
Hey Vered,
I am very glad to see your response, I'm going to try it.

**Comment by wt123u** [comment]
Hi @vered1986 ,
I want to know that how to create data set . it's referred that distant supervision was used in the paper,  can you provide some details ?  I need to extract a specific domain knowledge base from yago.

**Comment by vered1986** [comment]
Hi @wt123u,

The dataset is available [here](https://github.com/vered1986/HypeNET/blob/v2/dataset/datasets.rar). If you want to create a different dataset in the same matter, you can download the triplet files from the various resources (e.g Yago), and select the pairs of entities that are connected by relevant properties. We selected these properties from our previous work, and used those stated in the paper. We used other properties as negative examples. Finally, to make sure that the dataset examples have paths in the corpus (which you may or may not want to do), you can use [this script](https://github.com/vered1986/HypeNET/blob/v2/dataset/filter_noun_pairs.py). I hope this helps.

**Comment by wt123u** [comment]
Hi @vered1986 
The dataset which is contained in dataset_rnd/ or dataset_lex/ is origional or filtered ? I can't understand the lexical splitting with dataset.

**Comment by wt123u** [comment]
Hi @vered1986 
There is some difference  between you afford path and generated by parsed_wikipedia.py, yours like 'X/NOUN/nsubj/>_from/ADP/ROOT/^_another/DET/det/V_Y/NOUN/pobj/<' and generated like 'X/PROPN/compound>_park/PROPN/ROOT_<Y/PROPN/compound',   the direction's location is different.

**Comment by wt123u** [comment]
There is some difference between you afford path and generated by parsed_wikipedia.py, yours like 'X/NOUN/nsubj/>_from/ADP/ROOT/^_another/DET/det/V_Y/NOUN/pobj/<' and generated like 'X/PROPN/compound>_park/PROPN/ROOT_<Y/PROPN/compound',  the direction's location is different.

**Comment by wt123u** [comment]
There is some difference between you afford path and generated by parsed_wikipedia.py, yours like 'X/NOUN/nsubj/>_from/ADP/ROOT/^_another/DET/det/V_Y/NOUN/pobj/<' and generated like 'X/PROPN/compound>_park/PROPN/ROOT_<Y/PROPN/compound', the direction's location is different.

**Comment by vered1986** [comment]
Filtered. Lexical split means that the train, test, and validation sets consist of distinct vocabularies (e.g if "cat" is in the training set, it can't be in the validation or test sets). 

Right, sorry about that, the first format (with the direction as a fourth component after the slash) is the updated one. For consistency I suggest that you use the [LexNET code](https://github.com/vered1986/LexNET) which is more updated, unless you want to reproduce the results from the HypeNET paper (and then you can't use the LexNET processed corpus and pretrained models).

**Comment by wt123u** [comment]
Hi @vered1986
Oh , I see, thank you so much.
You mean that the corpus afforded as resource V1 or V2 was processed by LexNet ? My task is to identify hypernymy in specific domains, i think that using the HypeNet will be better, do you think so ? I am going to reproduce the results of paper, but my results was much worse. As picture shows: rnd_path means dataset using dataset_rnd, method using path_based. ps: the corpus was resource V1. 
![Uploading result_experience.png…]()

**Comment by wt123u** [comment]
Hi @vered1986
Oh , I see, thank you so much.
You mean that the corpus afforded as resource V1 or V2 was processed by LexNet ? My task is to identify hypernymy in specific domains, i think that using the HypeNet will be better, do you think so ? I am going to reproduce the answer of paper, but the result was much worse. As follows or pictures: rnd_path means dataset using dataset_rnd, method using path_based. 


![result_experience](https://user-images.githubusercontent.com/18399135/41197991-0531938a-6ca0-11e8-992c-362b792a15ce.png)
]()

**Comment by vered1986** [comment]
You may use the LexNET code, you should get comparable (although not identical) numbers. There are not so many changes, and it may be that I forgot to add some of the updates to the HypeNET repository. 

These numbers are way too low for the path-based method, clearly it's getting some pairs randomly correct. Based on the [other open issue](https://github.com/vered1986/HypeNET/issues/5), I can guess your corpus file is not built correctly. I'm closing this issue for now until we solve the other one.
